server {
    listen       80;
    listen  [::]:80;
    # 重定向到https
    server_name  huli66.com www.huli66.com;
    return 301 https://$server_name$request_uri;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /static {
        alias /usr/share/nginx/static;
    }

}

